### ISSUE TITLE
Instructor Feedback - Checkpoint 2

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [kheise91/IndieProject#3]
Kevin, you have a good start here, and it looks like you've been doing a good job keeping your time log and project plan, current.  I didn't find any System.out.printlns hanging about; you've done a good keeping your code clean there!  Seems like you are a bit behind what you had originally scheduled out, but I know you can catch back up to plan!

- [x] Looks like hibernate log files are going to a strange location: ${filepath}.  Check the log4j2.properties file to make sure the path variable name is correct. Once you have those logs doing to your logs directory, then delete the ${file path} folder.
- [x] ERD - looking good!  One table that we'll need yet is a role table (more on this in the week 7 authentication demo/notes).
- [x]  Screen design is solid so far. I think maybe screens for finding friends or connecting with other concert-goers may be missing?  Looks like it's on your plan to flush this out yet.
- [x] Add a .equals() method to your entities to make them easier to compare when unit testing.
- [x] Time to start thinking about implementing the generic dao (since all daos will essentially be the same, you can save a lot of time by using a single dao). You should leave all unit tests, just modify them to use the generic dao. Any new entities, should likewise be unit tested with regard to the hibernate/db "stuff”.
- [x] It's also time to start thinking about what classes you will need to create yet. Which controllers and which additional entities, for example. 
- [x] Remember to check off completed issue items using - [x], and then close the issue when all tasks are complete (including peer reviews).

**Comment by kheise91** [comment]
Didn't get around to implementing .equals() methods in my testing
